swagger: '2.0'
info:
  title: "Ecommerce API"
  description: "API that includes resources to manage an ecommerce website"
  version: "1.0.0"
host: "127.0.0.1:5000" #working on local host
schemes:
  - "http"
consumes:
  - "application/json"
produces:
  - "application/json"

securtiyDefinitions:
  beaerAuth:
    type: apiKey
    name: Authorization
    in: header

#Routes
paths:
  #Login Path
  /customers/login: #the specific URL endpoint
    post: #what kind of request you are sending
      tags:
        - Customer #Creayed a category for this route that can be reused on like routes
      summary: "Login endpoint (generates token)"
      description: "Endpoint for user authentication, and token generation."
      parameters:
        - in: "body"
          name: "body"
          description: "credentials for login (email and password)"
          required: true
          schema:
            $ref: "#/definitions/LoginPayload"

      responses:
          200:
          description: "Login successful"
          schema:
            $ref: "#/definitions/LoginResponse"
          examples:
            application/json:
              token: "oihjsfviuhwrtjeofrw;rk....."
              message: "successfully logged in"
              status: "success"

  #GetAllCustomers Path
  /customers:
    get:
      tags:
        - Customer
      summary: "Retrieve a list of customer objects"
      description: "Endpoint to retrieve all the customers, requires token authentication"
      security:
        - bearerAuth:
      responses:
        200:
          description: "Successfully retrieved all customers"
          schema:
            $ref: "#/definitions/GetAllCustomers"
          examples:
            application/json:
              name: "John Wick"
              email: "jwick@mail.com"
              phone: "1234567890"
              username: "jwick"
              admin: 0
#Payloads and Responses
definitions: 
    #Login Definitions
  LoginPayload:
    type: "object" #sending a JSON object
    properties:
      email:
        type: "string"
        description: "email"
      password:
        type: "string"
        description: "password"
    required:
    - "email"
    - "password"

  LoginResponse:
    type: "object"
    properties:
      token:
        type: "string"
        description: "Authentication token on successful login"
      message:
        type: "string"
        description: "Message indicating success or failure"
      status:
        type: "status"
        description: "Status of operation"
      required:
      - "message"
      - "status"

    # Get All Customers Response
  GetCustomersResponse:
    type: "object"
    properties:
      name:
        type: "string"
        description: "customer name"
      phone:
        type: "string"
        description: "customer phone"
      email:
        type: "string"
        description: "customer email"
      password:
        type: "string"
        description: "customer password"
      username:
        type: "string"
        description: "customer username"
      admin:
        type: "integer"
        description: "Admin permission"
      
